Fixes placement of Emojis and Tweet card
prastut/bubble-frontend pull request #43
Opened 2017-08-11 19:20 UTC by arihantparsoya

#40 

* Tweet Display Card placement: It should open where the Bubble is
*  Increase Tweet Card Display Time to 10 seconds

2017-08-11 19:20 UTC, arihantparsoya commented
@prastut , @KumShivam

2017-08-12 04:41 UTC, prastut requested changes
Hardcoding values is a nono :/

2017-08-12 04:41 UTC, prastut commented on public/js/app/utils/linegraph.js
> +                        .style("top", (yCoords[1] + 195) + "px")
Hardcoding would be a problem since this coordinate won't work on every device.

2017-08-12 04:42 UTC, closed without merging

2017-08-12 04:44 UTC, prastut commented on public/js/app/utils/linegraph.js
> +                        .style("top", (yCoords[1] + 195) + "px")
@parsoyaarihant Try this?
https://www.sitepoint.com/how-to-translate-from-dom-to-svg-coordinates-and-back-again/